format = """
[░▒▓](#788F48)\
[ \ue712 ](bg:#648519 fg:#b7b8ba)\
[](bg:#648519 fg:#648519)\
$directory\
[](bg:#7D9F3F fg:#648519)\
$git_branch\
$git_status\
[](bg:#8D995B fg:#7D9F3F)\
$python\
$rust\
$golang\
$c\
[](fg:#8D995B bg:#648519)\
$time\
[ ](fg:#648519)\
\n$character
"""
[username]
style_root="green bold"
format= "[$user]($style) "
disabled= false
show_always = true

[directory]
style = "fg:#e3e5e5 bg:#648519"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = ".../"


[git_branch]
symbol = ""
style = "bg:#7D9F3F"
format = '[[ $symbol $branch ](fg:#b7b8ba bg:#7D9F3F)]($style)'

[git_status]
style = "bg:#7D9F3F"
format = '[[($all_status$ahead_behind )](fg:#b7b8ba bg:#7D9F3F)]($style)'

[rust]
symbol = ""
style = "bg:#8D995B"
format = '[[ $symbol ($version) ](fg:#b7b8ba bg:#8D995B)]($style)'

[c]
symbol = "\ue61e"
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#b7b8ba bg:#212736)]($style)'

[golang]
symbol = ""
style = "bg:#8D995B"
format = '[[ $symbol ($version) ](fg:#b7b8ba bg:#8D995B)]($style)'

[python]

format = '[[ $symbol ($version) (\($virtualenv\)) ](fg:#b7b8ba bg:#8D995B)]($style)'


[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#648519"
format = '[[  $time ](fg:#b7b8ba bg:#648519)]($style)'
