'$help' = 'https://aka.ms/terminal-documentation'
'$schema' = 'https://aka.ms/terminal-profiles-schema'
alwaysShowTabs = false
defaultProfile = '{574e775e-4f2a-5b96-ac1e-a2962a402336}'
showTabsInTitlebar = false
themes = []
'warning.confirmCloseAllTabs' = false

[[actions]]
command = 'tabSearch'
id = 'User.tabSearch'

[[keybindings]]
id = 'Terminal.ClosePane'
keys = 'ctrl+shift+w'

[[keybindings]]
id = 'Terminal.MoveFocusLeft'
keys = 'ctrl+h'

[[keybindings]]
id = 'Terminal.MoveFocusDown'
keys = 'ctrl+j'

[[keybindings]]
id = 'Terminal.MoveFocusUp'
keys = 'ctrl+k'

[[keybindings]]
id = 'Terminal.MoveFocusRight'
keys = 'ctrl+l'

[[keybindings]]
id = 'Terminal.OpenNewTabDropdown'
keys = 'ctrl+shift+n'

[[keybindings]]
id = 'Terminal.SplitPaneDown'
keys = 'ctrl+shift+minus'

[[keybindings]]
id = 'Terminal.PrevTab'
keys = 'ctrl+shift+tab'

[[keybindings]]
id = 'Terminal.NextTab'
keys = 'ctrl+tab'

[[keybindings]]
id = 'User.tabSearch'
keys = 'ctrl+shift+t'

[[keybindings]]
id = 'Terminal.SwapPaneUp'
keys = 'alt+shift+k'

[[keybindings]]
id = 'Terminal.ToggleCommandPalette'
keys = 'alt+x'

[[keybindings]]
id = 'Terminal.TogglePaneZoom'
keys = 'ctrl+shift+z'

[[keybindings]]
id = 'Terminal.SwapPaneLeft'
keys = 'alt+shift+h'

[[keybindings]]
id = 'Terminal.SwapPaneDown'
keys = 'alt+shift+j'

[[keybindings]]
id = 'Terminal.SwapPaneRight'
keys = 'alt+shift+l'

[[newTabMenu]]
profile = '{61c54bbd-c2c6-5271-96e7-009a87ff44bf}'
type = 'profile'

[[newTabMenu]]
profile = '{574e775e-4f2a-5b96-ac1e-a2962a402336}'
type = 'profile'

[[newTabMenu]]
profile = '{9f2d0e2e-4ed0-4aa3-a1a7-000000000001}'
type = 'profile'

[[newTabMenu]]
profile = '{9f2d0e2e-4ed0-4aa3-a1a7-000000000002}'
type = 'profile'

[[newTabMenu]]
type = 'separator'

[[newTabMenu]]
profile = '{9f2d0e2e-4ed0-4aa3-a1a7-000000000003}'
type = 'profile'

[[newTabMenu]]
profile = '{9f2d0e2e-4ed0-4aa3-a1a7-000000000004}'
type = 'profile'

[[newTabMenu]]
profile = '{58ad8b0c-3ef8-5f4d-bc6f-13e4c00f2530}'
type = 'profile'

[profiles]
[profiles.defaults]
colorScheme = 'Catppuccin Mocha'
cursorColor = '#F5E0E6'
cursorShape = 'bar'
opacity = 90
padding = '8'
tabColor = '#1E1E2E'
useAcrylic = true

[profiles.defaults.font]
face = 'RobotoMono Nerd Font'
size = 10
weight = 'bold'

[[profiles.list]]
commandline = 'powershell.exe -NoLogo'
guid = '{61c54bbd-c2c6-5271-96e7-009a87ff44bf}'
hidden = false
name = 'PowerShell'
startingDirectory = '%USERPROFILE%'

[[profiles.list]]
commandline = 'pwsh.exe -NoLogo'
guid = '{574e775e-4f2a-5b96-ac1e-a2962a402336}'
hidden = false
name = 'PowerShell 7'
source = 'Windows.Terminal.PowershellCore'
startingDirectory = '%USERPROFILE%'

[[profiles.list]]
commandline = "pwsh.exe -NoLogo -NoExit -Command \"Import-Module \\\"${env:ProgramFiles(x86)}\\Microsoft Visual Studio\\18\\BuildTools\\Common7\\Tools\\Microsoft.VisualStudio.DevShell.dll\\\"; Enter-VsDevShell 6c43edf9; $host.UI.RawUI.WindowTitle = 'Developer PowerShell'\""
guid = '{9f2d0e2e-4ed0-4aa3-a1a7-000000000001}'
hidden = false
name = 'Developer PowerShell'
startingDirectory = '%WEZTERM_GIT_ROOT%'

[[profiles.list]]
commandline = 'pwsh.exe -NoLogo -NoExit -Command "& \"$env:USERPROFILE\miniconda3\shell\condabin\conda-hook.ps1\"; conda activate base"'
guid = '{9f2d0e2e-4ed0-4aa3-a1a7-000000000002}'
hidden = false
name = 'Conda PowerShell'
startingDirectory = '%WEZTERM_GIT_ROOT%\Machine Learning'

[[profiles.list]]
commandline = 'cmd.exe /k D:\VisualStudio2022\VC\Auxiliary\Build\vcvars64.bat'
guid = '{9f2d0e2e-4ed0-4aa3-a1a7-000000000003}'
hidden = false
name = 'X64 Native Tools VS 2022 - D'
startingDirectory = '%USERPROFILE%'

[[profiles.list]]
commandline = 'cmd.exe /k C:\VisualStudio2022\VC\Auxiliary\Build\vcvars64.bat'
guid = '{9f2d0e2e-4ed0-4aa3-a1a7-000000000004}'
hidden = false
name = 'X64 Native Tools VS 2022 - C'
startingDirectory = '%USERPROFILE%'

[[schemes]]
background = '#1E1E2E'
black = '#45475A'
blue = '#89B4FA'
brightBlack = '#585B70'
brightBlue = '#89B4FA'
brightCyan = '#94E2D5'
brightGreen = '#A6E3A1'
brightPurple = '#F5C2E7'
brightRed = '#F38BA8'
brightWhite = '#A6ADC8'
brightYellow = '#F9E2AF'
cursorColor = '#F5E0E6'
cyan = '#94E2D5'
foreground = '#CDD6F4'
green = '#A6E3A1'
name = 'Catppuccin Mocha'
purple = '#F5C2E7'
red = '#F38BA8'
selectionBackground = '#585B70'
white = '#BAC2DE'
yellow = '#F9E2AF'
