##########################################################
##                                                      ##
##              My TMUX Config                          ##
##                                                      ##
##########################################################

# set Status bar options 
set -g status-position top
set -g base-index 1
set -g pane-base-index 1


set -g mouse on
set -s escape-time 50
set -s default-terminal 'xterm-256color'

# Map pane selection to more easy vim like bindings
setw -g mode-keys vi

bind-key -n 'M-h' select-pane -L
bind-key -n 'M-j' select-pane -D
bind-key -n 'M-k' select-pane -U
bind-key -n 'M-l' select-pane -R

# Map pane resize
bind-key -r -T prefix 'M-h' resize-pane -L 5
bind-key -r -T prefix 'M-j' resize-pane -D 5
bind-key -r -T prefix 'M-k' resize-pane -U 5
bind-key -r -T prefix 'M-l' resize-pane -R 5


set -g @plugin 'catppuccin/tmux#v2.1.1'
set -g @catppuccin_flavour 'frappe'
set -g @catppuccin_window_status_style 'rounded' 

set -g @catppuccin_window_text " #W" 
set -g @catppuccin_window_current_text " #W" 
set -g @catppuccin_status_modules_right "host uptime application session"
set -g status-right-length 100
set -g status-left-length 100
set -g status-left "" 
set -gF status-right "#{@catppuccin_status_directory}" 
set -gF status-right "#{@catppuccin_status_user}" 
set -gF status-right "#{@catppuccin_status_host}" 


# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
set -g @plugin 'tmux-plugins/tpm'
run '~/.tmux/plugins/tpm/tpm'
